table fakt_chpu_kst
	lineageTag: e763f5b3-c0cb-46f8-ad58-d17343cd8446

	measure 'Debug Anzahl Zeilen fakt_chpu_kst' =
			
			COUNTROWS('fakt_chpu_kst')
		formatString: 0
		lineageTag: b8cfa0c2-d097-408c-b292-c3ecaacc0296

	measure 'ZE Ist KST' = ```
			
			SUM('fakt_chpu_kst'[ze_ist])
			
			```
		lineageTag: fccb0d4f-1738-4b42-a5f8-77788286c0f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ZE Soll KST' = ```
			
			SUM('fakt_chpu_kst'[ze_soll])
			
			```
		lineageTag: ab6c9487-6642-4185-a982-8a510ce2cf5c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Ist KST' = ```
			
			SUM('fakt_chpu_kst'[anmin_ist])
			
			```
		lineageTag: 29cdda0b-ee97-44c3-a4e4-f5f6c3da69c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll KST' = ```
			
			SUM('fakt_chpu_kst'[anmin_soll])
			
			```
		lineageTag: b0c13480-4e9c-4df2-adbe-4655ac234256

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll ohne Ratio KST' = ```
			
			SUM('fakt_chpu_kst'[anmin_soll_ohne_ratio])
			
			```
		lineageTag: 00ce4627-464a-476a-948a-c8922ee6f05c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Ist D KST' =
			
			SUM('fakt_chpu_kst'[anmin_ist_d])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000010

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Ist DI KST' =
			
			SUM('fakt_chpu_kst'[anmin_ist_di])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000011

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Ist I KST' =
			
			SUM('fakt_chpu_kst'[anmin_ist_i])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000012

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll D KST' =
			
			SUM('fakt_chpu_kst'[anmin_soll_d])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll DI KST' =
			
			SUM('fakt_chpu_kst'[anmin_soll_di])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000014

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll I KST' =
			
			SUM('fakt_chpu_kst'[anmin_soll_i])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000015

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll ohne Ratio D KST' =
			
			SUM('fakt_chpu_kst'[anmin_soll_ohne_ratio_d])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000016

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll ohne Ratio DI KST' =
			
			SUM('fakt_chpu_kst'[anmin_soll_ohne_ratio_di])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000017

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll ohne Ratio I KST' =
			
			SUM('fakt_chpu_kst'[anmin_soll_ohne_ratio_i])
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000018

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Ist KST' = ```
			
			DIVIDE(
			    [AnMin Ist KST],
			    [ZE Ist KST]
			)
			
			```
		lineageTag: 357463ab-1333-4018-90e6-0e9100a68511

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Soll KST' = ```
			
			DIVIDE(
			    [AnMin Soll KST],
			    [ZE Ist KST]
			)
			
			```
		lineageTag: 4f1b6b9d-b838-45bc-9ded-308893c7963a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Soll ohne Ratio KST' = ```
			
			DIVIDE(
			    [AnMin Soll ohne Ratio KST],
			    [ZE Ist KST]
			)
			
			```
		lineageTag: 84034f1b-75ca-4fc0-914d-a41f19a5588a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Ist D KST' =
			
			DIVIDE( [AnMin Ist D KST], [ZE Ist KST] )
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000053

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Ist DI KST' =
			
			DIVIDE( [AnMin Ist DI KST], [ZE Ist KST] )
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000054

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Ist I KST' =
			
			DIVIDE( [AnMin Ist I KST], [ZE Ist KST] )
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000055

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ratio Ist KST' =
			
			DIVIDE(
			    [CHPU Soll ohne Ratio KST] - [CHPU Ist KST],
			    [CHPU Soll ohne Ratio KST]
			) * 100
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000001

	measure 'Ratio Soll KST' =
			
			DIVIDE(
			    [CHPU Soll ohne Ratio KST] - [CHPU Soll KST],
			    [CHPU Soll ohne Ratio KST]
			) * 100
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000002

	measure 'Delta Ratio KST' =
			
			[Ratio Ist KST] - [Ratio Soll KST]
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000003

	measure 'Ratio Ist D KST' =
			
			VAR _chpu_0 = DIVIDE( [AnMin Soll ohne Ratio D KST], [ZE Ist KST] )
			VAR _chpu_ist = DIVIDE( [AnMin Ist D KST], [ZE Ist KST] )
			RETURN
			DIVIDE( _chpu_0 - _chpu_ist, _chpu_0 ) * 100
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000050

	measure 'Ratio Ist DI KST' =
			
			VAR _chpu_0 = DIVIDE( [AnMin Soll ohne Ratio DI KST], [ZE Ist KST] )
			VAR _chpu_ist = DIVIDE( [AnMin Ist DI KST], [ZE Ist KST] )
			RETURN
			DIVIDE( _chpu_0 - _chpu_ist, _chpu_0 ) * 100
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000051

	measure 'Ratio Ist I KST' =
			
			VAR _chpu_0 = DIVIDE( [AnMin Soll ohne Ratio I KST], [ZE Ist KST] )
			VAR _chpu_ist = DIVIDE( [AnMin Ist I KST], [ZE Ist KST] )
			RETURN
			DIVIDE( _chpu_0 - _chpu_ist, _chpu_0 ) * 100
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000052

	measure 'Delta AnMin KST' =
			
			[AnMin Ist KST] - [AnMin Soll KST]
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000020

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta AnMin D KST' =
			
			[AnMin Ist D KST] - [AnMin Soll D KST]
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000021

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta AnMin DI KST' =
			
			[AnMin Ist DI KST] - [AnMin Soll DI KST]
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000022

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta AnMin I KST' =
			
			[AnMin Ist I KST] - [AnMin Soll I KST]
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000023

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta CHPU KST' =
			
			[CHPU Ist KST] - [CHPU Soll KST]
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000024

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// YTD aus vorberechneter Dataflow-Spalte (Stand der letzten KW im Filterkontext)
	measure 'ZE Ist KST YTD' =
			
			VAR _kw = MAX('fakt_chpu_kst'[jahr_kw])
			RETURN
			CALCULATE(
			    SUM('fakt_chpu_kst'[ze_ist_ytd]),
			    'fakt_chpu_kst'[jahr_kw] = _kw
			)
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000030

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Ist KST YTD' =
			
			VAR _kw = MAX('fakt_chpu_kst'[jahr_kw])
			RETURN
			CALCULATE(
			    SUM('fakt_chpu_kst'[anmin_ist_ytd]),
			    'fakt_chpu_kst'[jahr_kw] = _kw
			)
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000032

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll KST YTD' =
			
			VAR _kw = MAX('fakt_chpu_kst'[jahr_kw])
			RETURN
			CALCULATE(
			    SUM('fakt_chpu_kst'[anmin_soll_ytd]),
			    'fakt_chpu_kst'[jahr_kw] = _kw
			)
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000033

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AnMin Soll ohne Ratio KST YTD' =
			
			VAR _kw = MAX('fakt_chpu_kst'[jahr_kw])
			RETURN
			CALCULATE(
			    SUM('fakt_chpu_kst'[anmin_soll_ohne_ratio_ytd]),
			    'fakt_chpu_kst'[jahr_kw] = _kw
			)
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000034

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Ist KST YTD' =
			
			IF(
			    [ZE Ist KST YTD] = 0,
			    BLANK(),
			    DIVIDE( [AnMin Ist KST YTD], [ZE Ist KST YTD] )
			)
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000035

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CHPU Soll KST YTD' =
			
			IF(
			    [ZE Ist KST YTD] = 0,
			    BLANK(),
			    DIVIDE( [AnMin Soll KST YTD], [ZE Ist KST YTD] )
			)
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000036

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ratio Ist KST YTD' =
			
			DIVIDE(
			    [AnMin Soll ohne Ratio KST YTD] - [AnMin Ist KST YTD],
			    [AnMin Soll ohne Ratio KST YTD]
			) * 100
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000037

	measure 'Ratio Soll KST YTD' =
			
			DIVIDE(
			    [AnMin Soll ohne Ratio KST YTD] - [AnMin Soll KST YTD],
			    [AnMin Soll ohne Ratio KST YTD]
			) * 100
		formatString: 0.00
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000038

	measure 'Ampel KST YTD' =
			
			IF(
			    ISBLANK([Ratio Ist KST YTD]) ||
			    ISBLANK([Ratio Soll KST YTD]),
			    BLANK(),
			    SWITCH(
			        TRUE(),
			        [Ratio Ist KST YTD] >= [Ratio Soll KST YTD], "grün",
			        [Ratio Ist KST YTD] >= 0, "gelb",
			        "rot"
			    )
			)
		lineageTag: b1b2c3d4-2001-4bbb-b001-000000000039

	column source_plant_id
		dataType: string
		lineageTag: b6f1657b-7920-431c-9d30-ad585001b2e6
		summarizeBy: none
		sourceColumn: source_plant_id

		annotation SummarizationSetBy = Automatic

	column kst_bezeichnung_kurz
		dataType: string
		lineageTag: 3fa05d37-823f-4929-80f5-b979d1e4fb0b
		summarizeBy: none
		sourceColumn: kst_bezeichnung_kurz

		annotation SummarizationSetBy = Automatic

	column jahr_kw
		dataType: int64
		formatString: 0
		lineageTag: bcd17dac-b5ba-428a-8d86-16f0789ee570
		summarizeBy: none
		sourceColumn: jahr_kw

		annotation SummarizationSetBy = User

	column ratio_soll_i
		dataType: double
		lineageTag: 008eecdf-69a8-4fbc-b355-23799cc36950
		summarizeBy: none
		sourceColumn: ratio_soll_i

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_soll_d
		dataType: double
		lineageTag: 89752128-68e3-4bd3-a108-1714d76da037
		summarizeBy: none
		sourceColumn: ratio_soll_d

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_soll_di
		dataType: double
		lineageTag: 9f1d0e33-4d89-482a-9af8-ebc32f3ca973
		summarizeBy: none
		sourceColumn: ratio_soll_di

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_i
		dataType: double
		lineageTag: ff3f6172-0e7d-4026-b6d2-95623b9c5785
		summarizeBy: sum
		sourceColumn: anmin_soll_i

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_di
		dataType: double
		lineageTag: ac38f519-1385-4ece-92db-b7512f2b32b3
		summarizeBy: sum
		sourceColumn: anmin_soll_di

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_d
		dataType: double
		lineageTag: 3075fbb1-0a19-4e01-918f-a1c043807eb3
		summarizeBy: sum
		sourceColumn: anmin_soll_d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ze_soll
		dataType: double
		lineageTag: 0519b5ec-2eca-4004-aaeb-15664dc2ec42
		summarizeBy: sum
		sourceColumn: ze_soll

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ze_ist
		dataType: double
		lineageTag: e58b4aab-0109-42c9-867f-d84a09cb9198
		summarizeBy: sum
		sourceColumn: ze_ist

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_ist_i
		dataType: double
		lineageTag: 5a476993-9c78-46f1-ac47-4df93d80445c
		summarizeBy: sum
		sourceColumn: anmin_ist_i

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_ist_d_di
		dataType: double
		lineageTag: a24e03b8-f096-4c3c-8522-4ff54599ec5c
		summarizeBy: sum
		sourceColumn: anmin_ist_d_di

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_ist_d
		dataType: double
		lineageTag: 95508ac0-8104-4892-82ab-efcc926b66e2
		summarizeBy: sum
		sourceColumn: anmin_ist_d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_ist_di
		dataType: double
		lineageTag: 75789ff4-227a-4afe-aa6f-1555e1a6a1e9
		summarizeBy: sum
		sourceColumn: anmin_ist_di

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll
		dataType: double
		lineageTag: 2f0190d4-3084-457c-ba26-a5e050b3707c
		summarizeBy: sum
		sourceColumn: anmin_soll

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_ist
		dataType: double
		lineageTag: 31c05ce1-6840-4a8a-9d37-a32951c88090
		summarizeBy: sum
		sourceColumn: anmin_ist

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_ohne_ratio_d
		dataType: double
		lineageTag: 0d8a5f7c-ec19-424b-8610-eb3902cd4772
		summarizeBy: sum
		sourceColumn: anmin_soll_ohne_ratio_d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_ohne_ratio_di
		dataType: double
		lineageTag: 57d3813b-0208-4973-b7f8-47d73010a467
		summarizeBy: sum
		sourceColumn: anmin_soll_ohne_ratio_di

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_ohne_ratio_i
		dataType: double
		lineageTag: a53d38b2-0c74-45dc-83d5-840e42da7250
		summarizeBy: sum
		sourceColumn: anmin_soll_ohne_ratio_i

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_ohne_ratio
		dataType: double
		lineageTag: e6f6a39e-bd5f-4553-9f73-8d642610db66
		summarizeBy: sum
		sourceColumn: anmin_soll_ohne_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_ist_d
		dataType: double
		lineageTag: 1d49ced6-b6a7-4383-aaaf-5b35152d1830
		summarizeBy: none
		sourceColumn: ratio_ist_d

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_ist_di
		dataType: double
		lineageTag: 203e587f-34bf-4232-aaa6-6a0aa43b31f4
		summarizeBy: none
		sourceColumn: ratio_ist_di

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_ist_i
		dataType: double
		lineageTag: ed1a98df-cd7e-4c9a-ab2e-9aa849165428
		summarizeBy: none
		sourceColumn: ratio_ist_i

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_ist
		dataType: double
		lineageTag: 1272122a-1832-4a86-b003-f439d7b8e374
		summarizeBy: none
		sourceColumn: ratio_ist

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_ist_d
		dataType: double
		lineageTag: e3e38a9b-8497-4c46-9b71-930704179c4f
		summarizeBy: none
		sourceColumn: chpu_ist_d

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_ist_di
		dataType: double
		lineageTag: c68f50b0-73ab-4312-98bc-1b0ce9c7e756
		summarizeBy: none
		sourceColumn: chpu_ist_di

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_ist_i
		dataType: double
		lineageTag: 55c1e0f3-a602-4638-a652-898db21f5a36
		summarizeBy: none
		sourceColumn: chpu_ist_i

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_ist
		dataType: double
		lineageTag: e1a93d24-8bfd-4a05-a5f2-00723624e1ca
		summarizeBy: none
		sourceColumn: chpu_ist

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_soll
		dataType: double
		lineageTag: 2ace5abf-c430-4a07-a7e8-c8cffd17034b
		summarizeBy: none
		sourceColumn: chpu_soll

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_soll
		dataType: double
		lineageTag: 3ebfbf96-3374-4640-9b8e-6c774c5b6282
		summarizeBy: none
		sourceColumn: ratio_soll

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_soll_ohne_ratio
		dataType: double
		lineageTag: d57fb349-13d7-4c3e-bd03-b27089d4c74b
		summarizeBy: none
		sourceColumn: chpu_soll_ohne_ratio

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ze_ist_ytd
		dataType: double
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000001
		summarizeBy: sum
		sourceColumn: ze_ist_ytd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ze_soll_ytd
		dataType: double
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000002
		summarizeBy: sum
		sourceColumn: ze_soll_ytd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_ist_ytd
		dataType: double
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000003
		summarizeBy: sum
		sourceColumn: anmin_ist_ytd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_ytd
		dataType: double
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000004
		summarizeBy: sum
		sourceColumn: anmin_soll_ytd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anmin_soll_ohne_ratio_ytd
		dataType: double
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000005
		summarizeBy: sum
		sourceColumn: anmin_soll_ohne_ratio_ytd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_ist_ytd
		dataType: double
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000006
		summarizeBy: none
		sourceColumn: chpu_ist_ytd

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chpu_soll_ytd
		dataType: double
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000007
		summarizeBy: none
		sourceColumn: chpu_soll_ytd

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ratio_ist_ytd
		dataType: double
		formatString: 0.00
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000008
		summarizeBy: none
		sourceColumn: ratio_ist_ytd

		annotation SummarizationSetBy = User

	column ratio_soll_ytd
		dataType: double
		formatString: 0.00
		lineageTag: d1e2f3a4-4001-4ddd-b001-000000000009
		summarizeBy: none
		sourceColumn: ratio_soll_ytd

		annotation SummarizationSetBy = User

	partition fakt_chpu_kst = m
		mode: import
		source = ```
				let
				  Quelle = PowerPlatform.Dataflows([]),
				  #"Navigation 1" = Quelle{[Id = "Workspaces"]}[Data],
				  #"Navigation 2" = #"Navigation 1"{[workspaceId = "c5f886de-fae0-47a0-a39c-88802ced5740"]}[Data],
				  #"Navigation 3" = #"Navigation 2"{[dataflowId = "f86c3ce9-edc9-4f19-a809-f03028f2103b"]}[Data],
				  #"Navigation 4" = #"Navigation 3"{[entity = "fakt_chpu_kst", version = ""]}[Data],
				
				  // ─────────────────────────────────────────────────────────────────────
				  // Simulation der künftigen Dataflow-Spalten (YTD je Werk × KST × KW).
				  // Sobald der Dataflow diese Spalten selbst liefert, entfallen alle
				  // Schritte ab hier ersatzlos (gleiche Spaltennamen).
				  // ─────────────────────────────────────────────────────────────────────
				  MitJahr = Table.AddColumn(#"Navigation 4", "_jahr", each Number.IntegerDivide([jahr_kw], 100), Int64.Type),
				
				  Gruppiert = Table.Group(
				    MitJahr,
				    {"source_plant_id", "kst_bezeichnung_kurz", "_jahr"},
				    {{"_grp", (t) =>
				      let
				        Sortiert = Table.Sort(t, {{"jahr_kw", Order.Ascending}}),
				        MitYtd = Table.AddColumn(
				          Sortiert,
				          "_ytd",
				          (zeile) =>
				            let
				              Bis = Table.SelectRows(Sortiert, each [jahr_kw] <= zeile[jahr_kw])
				            in
				              [
				                ze_ist_ytd = List.Sum(Bis[ze_ist]),
				                ze_soll_ytd = List.Sum(Bis[ze_soll]),
				                anmin_ist_ytd = List.Sum(Bis[anmin_ist]),
				                anmin_soll_ytd = List.Sum(Bis[anmin_soll]),
				                anmin_soll_ohne_ratio_ytd = List.Sum(Bis[anmin_soll_ohne_ratio])
				              ]
				        ),
				        Expandiert = Table.ExpandRecordColumn(
				          MitYtd,
				          "_ytd",
				          {"ze_ist_ytd", "ze_soll_ytd", "anmin_ist_ytd", "anmin_soll_ytd", "anmin_soll_ohne_ratio_ytd"}
				        )
				      in
				        Expandiert,
				      type table}}
				  ),
				
				  Kombiniert = Table.Combine(Gruppiert[_grp]),
				
				  // Abgeleitete YTD-Kennzahlen (CHPU/Ratio) auf Zeilenebene
				  ChpuIstYtd = Table.AddColumn(Kombiniert, "chpu_ist_ytd", each if [ze_ist_ytd] = null or [ze_ist_ytd] = 0 then null else [anmin_ist_ytd] / [ze_ist_ytd], type nullable number),
				  ChpuSollYtd = Table.AddColumn(ChpuIstYtd, "chpu_soll_ytd", each if [ze_ist_ytd] = null or [ze_ist_ytd] = 0 then null else [anmin_soll_ytd] / [ze_ist_ytd], type nullable number),
				  RatioIstYtd = Table.AddColumn(ChpuSollYtd, "ratio_ist_ytd", each if [anmin_soll_ohne_ratio_ytd] = null or [anmin_soll_ohne_ratio_ytd] = 0 then null else ([anmin_soll_ohne_ratio_ytd] - [anmin_ist_ytd]) / [anmin_soll_ohne_ratio_ytd] * 100, type nullable number),
				  RatioSollYtd = Table.AddColumn(RatioIstYtd, "ratio_soll_ytd", each if [anmin_soll_ohne_ratio_ytd] = null or [anmin_soll_ohne_ratio_ytd] = 0 then null else ([anmin_soll_ohne_ratio_ytd] - [anmin_soll_ytd]) / [anmin_soll_ohne_ratio_ytd] * 100, type nullable number),
				
				  OhneJahr = Table.RemoveColumns(RatioSollYtd, {"_jahr"}),
				
				  Typisiert = Table.TransformColumnTypes(
				    OhneJahr,
				    {
				      {"ze_ist_ytd", type nullable number}, {"ze_soll_ytd", type nullable number},
				      {"anmin_ist_ytd", type nullable number}, {"anmin_soll_ytd", type nullable number},
				      {"anmin_soll_ohne_ratio_ytd", type nullable number}
				    }
				  )
				in
				  Typisiert
				```

	annotation PBI_ResultType = Table
